## Numpy

NumPy is a fundamental library for scientific computing in Python. It provide support for arrays and matrices, along with a collection of mathematical functions to operate on these data structure. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
# NumPy
import numpy as np

# Creating Arrays using numpy
# 1D Array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
print(arr1.shape)       # (6,) whenever there is a single dimension only one number is given

(6,)


In [4]:
# 2D Array

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)       # 1 Row and 5 Columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
np.arange(0, 10, 2)         # np.arange(start, stop, step) creates an array with regularly spaced values.

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))      # Creates a NumPy array filled with ones, having 3 rows and 4 columns.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)           # Creates an Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attribute of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Number of Dimension: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data Type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimension:  2
Size (number of elements):  6
Data Type:  int64
Item size (in bytes):  8


In [17]:
# Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [ ]:
# Element wise Addition
print("Addition: ", arr1 + arr2)

Addition:  [11 22 33 44 55]


In [ ]:
# Element wise Subtraction
print("Subtraction: ", arr1-arr2)

Subtraction:  [ -9 -18 -27 -36 -45]


In [20]:
# Element wise Multiplication
print("Multiplication: ", arr1 * arr2)

Multiplication:  [ 10  40  90 160 250]


In [21]:
# Elements wise Division
print("Division: ", arr1/arr2)

Division:  [0.1 0.1 0.1 0.1 0.1]


In [22]:
# Universal Function
arr = np.array([1,2,3,4,5])

# Square Root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
# Array Slicing and Indexing

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [31]:
print(arr[0][0])

1


In [28]:
arr[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [34]:
# Modify Array Element

arr[0,0] = 10000
print(arr)

[[10000     2     3     4     5]
 [    6     7     8     9    10]
 [   11    12    13    14    15]]


In [37]:
import numpy as np

# Sample data: 
# rows = samples, columns = features
# Let's say [height (cm), weight (kg), age (years)]
data = np.array([
    [170, 65, 30],
    [160, 70, 25],
    [180, 80, 35],
    [175, 75, 28]
])

print("Original Data:\n", data)

# Compute mean and std deviation for each column (feature)
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

print("\nMean:\n", mean)
print("Standard Deviation:\n", std_dev)

# Normalize each feature column-wise
normalized_data = (data - mean) / std_dev
print("\nNormalized Data:\n", normalized_data)


Original Data:
 [[170  65  30]
 [160  70  25]
 [180  80  35]
 [175  75  28]]

Mean:
 [171.25  72.5   29.5 ]
Standard Deviation:
 [7.39509973 5.59016994 3.64005494]

Normalized Data:
 [[-0.16903085 -1.34164079  0.13736056]
 [-1.52127766 -0.4472136  -1.23624508]
 [ 1.18321596  1.34164079  1.5109662 ]
 [ 0.50709255  0.4472136  -0.41208169]]


In [ ]:
# Sample data
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)

# Median
median = np.median(data)

# Mode (manual way using numpy)
values, counts = np.unique(data, return_counts=True)
# values: sorted unique numbers → [1, 2, 4, 5, 7, 9]
# counts: how many times each appears → [1, 3, 2, 2, 1, 1]
# np.argmax(counts): index of max count → 1 → value is 2

mode = values[np.argmax(counts)]

print("Data: ", data)
print("Mean: ", mean)
print("Median: ", median)
print("Mode: ", mode)


Data:  [ 1  2  3  4  5  6  7  8  9 10]
Mean:  5.5
Median:  5.5
Mode:  1
